### ISSUE TITLE
[AgeEstimation] Different phaleron-ae namespaces

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#189]
There are some classes under two distinct namespaces: 
I.e. the class `AgeEstimationProcess` exists as 

1. `<http://w3id.org/rdfbones/anthrograph/app/phaleron-ae/AgeEstimationProcess>`
2.  `<http://w3id.org/rdfbones/ext/phaleron-ae/AgeEstimationProcess>`

The problem is that the sex specific subclasses are defined within the first (wrong) namespace. However the second seems to be the correct one.

The problem also exists for `AgeEstimationDataset` and `PubicAgeEstimationDatasetSection`

Code to find stuff in the wrong namespace: 

```
PREFIX paeapp: <http://w3id.org/rdfbones/anthrograph/app/phaleron-ae/>
SELECT *  WHERE {
  ?s ?p ?o.
  FILTER( STRSTARTS(str(?s), str(paeapp:)) )
  } 
```

**Comment by cuboideum** [comment]
The correct prefix is the second, http://w3id.org/rdfbones/ext/phaleron-ae/. I need to eliminate the other one.

**Comment by zarquon42b** [comment]
But dont forget to update all subclass statements that are linked to the erroneous ones!

**Comment by cuboideum** [comment]
Pull request https://github.com/AnthroGraph/Phaleron-AppOntology/pull/40 fixes the issue in the Phaleron app ontology.

**Comment by cuboideum** [comment]
Commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/338b7c9e87be1bfb271be09c2121bd1f2333878e merges the changes into the robot branch of the Phaleron app ontology.

**Comment by zarquon42b** [comment]
> But dont forget to update all subclass statements that are linked to the erroneous ones!

... unfortunately this is now the case.

`SELECT *  WHERE { ?ageProcess rdfs:subClassOf*   <http://w3id.org/rdfbones/ext/phaleron-ae/AgeEstimationDataset> }`

Only yields: `http://w3id.org/rdfbones/anthrograph/app/phaleron-app/FemaleAgeEstimationDataset`

`PubicAgeEstimationDatasetSection` and `AgeEstimationProcess` lack the indeterminate versions of the subclasses.

**Comment by zarquon42b** [comment]
Also the superclasses are a mess: 
superclass of <`http://w3id.org/rdfbones/anthrograph/app/phaleron-app/IndeterminateSexPubicAgeEstimationDatasetSection>` is
` <http://w3id.org/rdfbones/ext/phaleron-ae/AgeEstimationProcess/PubicAgeEstimationDatasetSection>` 
instead of  `<http://w3id.org/rdfbones/ext/phaleron-ae/PubicAgeEstimationDatasetSection>` (without the `AgeEstimationProcess` in the URI)

Same problem with 

* `<http://w3id.org/rdfbones/anthrograph/app/phaleron-app/IndeterminateSexAgeEstimationProcess>`
* `<http://w3id.org/rdfbones/anthrograph/app/phaleron-app/IndeterminateSexAgeEstimationDataset>`
* <http://w3id.org/rdfbones/anthrograph/app/phaleron-app/MaleAgeEstimationDataset>

In all cases the namespace part of the superclass is wrong (additional string).

**Comment by cuboideum** [comment]
https://github.com/RDFBones/RDFBones-O/issues/189#issuecomment-1711856598 is fixed with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/1f18f2301efca95a5279a51a03a4a1a5e1086393.

**Comment by cuboideum** [comment]
https://github.com/RDFBones/RDFBones-O/issues/189#issuecomment-1711902983 is also fixed by these changes.

**Comment by cuboideum** [comment]
Issue fixed with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/1060b29609d7e5473e269ae10e3cba5fb4c153cd.

**Comment by zarquon42b** [comment]
No, it is still not fixed.
1. `PubicAgeEstimationDatasetSection` is still missing the subclass `IndeterminatePubicAgeEstimationDatasetSection`
2. `SpecimenOfBiologicalSexRole` is missing the subclass `IndeterminateSpecimenRole`

**Comment by cuboideum** [comment]
Pull request https://github.com/AnthroGraph/Phaleron-AppOntology/pull/42 fixes request 1. in the Phaleron app ontology.

**Comment by zarquon42b** [comment]
Almost there. 
`SpecimenOfBiologicalSexRole` is still missing the subclass `IndeterminateSpecimenRole`

**Comment by cuboideum** [comment]
Commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/f5fac10573346dfe3563d7a585c3704762fd4445 updates the Phaleron-AgeEstimation submodule of the Phaleron app ontology which fixes request 2. and closes the issue.

**Comment by zarquon42b** [comment]
Not so hasty, young man. 
The statement 
` <http://w3id.org/rdfbones/ext/phaleron-ae/SpecimenOfIndeterminateSexRole>  <http://w3id.org/rdfbones/anthrograph/app/phaleron-app/sexBasedContext> "ind" .`
is now missing.

**Comment by cuboideum** [comment]
Request from comment https://github.com/RDFBones/RDFBones-O/issues/189#issuecomment-1714162845 is fixed in the Phaleron app ontology with pull request https://github.com/AnthroGraph/Phaleron-AppOntology/pull/43.

**Comment by cuboideum** [comment]
Changes from pull request https://github.com/AnthroGraph/Phaleron-AppOntology/pull/43 are ported to the robot branch of the Phaleron app ontology with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/db3f2a60c876dc68ae1629a0bbb271b21acbb760.

This fixes the issue.
